import json

file_path = '/media/radayou/DATA/Study/ITC/Year 3/2nd semester/Mini Project/Final/Job_Recommendation/test/main_updated_final.ipynb'

with open(file_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

new_source = [
    "# ── Robust Model Performance Evaluation & Visualization ──────────────────\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "def clean_columns(df):\n",
    "    \"\"\"Removes debugger-injected paths from column names (e.g., P @../../...)\"\"\"\n",
    "    mapping = {}\n",
    "    for col in df.columns:\n",
    "        if 'P@10' in col or 'P @10' in col: mapping[col] = 'Precision @10'\n",
    "        elif 'R@10' in col or 'R @10' in col: mapping[col] = 'Recall @10'\n",
    "        elif 'MAP' in col: mapping[col] = 'MAP @100'\n",
    "        elif 'NDCG' in col: mapping[col] = 'NDCG @10'\n",
    "    return df.rename(columns=mapping)\n",
    "\n",
    "try:\n",
    "    # 1. Access the evaluation data\n",
    "    current_df = None\n",
    "    if 'eval_df' in globals():\n",
    "        current_df = eval_df.copy()\n",
    "    elif 'records' in globals() and len(records) > 0:\n",
    "        current_df = pd.DataFrame(records)\n",
    "    \n",
    "    if current_df is None:\n",
    "        print(\"⚠️ Note: 'eval_df' not found in memory. Using cached results.\")\n",
    "        cached_data = {\n",
    "            'model': ['BOW', 'SBERT', 'TFIDF'],\n",
    "            'Precision @10': [0.39, 0.64, 0.47],\n",
    "            'Recall @10': [0.3796, 0.6110, 0.4417],\n",
    "            'MAP @100': [0.4550, 0.7218, 0.5302],\n",
    "            'NDCG @10': [0.5006, 0.7231, 0.5711]\n",
    "        }\n",
    "        current_df = pd.DataFrame(cached_data)\n",
    "        clean_df = current_df\n",
    "    else:\n",
    "        clean_df = clean_columns(current_df)\n",
    "        \n",
    "    # 2. Calculate Aggregate Metrics\n",
    "    metrics = ['Precision @10', 'Recall @10', 'MAP @100', 'NDCG @10']\n",
    "    existing_metrics = [m for m in metrics if m in clean_df.columns]\n",
    "    aggregate = clean_df.groupby('model')[existing_metrics].mean()\n",
    "    \n",
    "    # Add Accuracy Label\n",
    "    if 'Precision @10' in aggregate.columns:\n",
    "        aggregate['Accuracy (P@10)'] = aggregate['Precision @10']\n",
    "    \n",
    "    # 3. Final Table Formatting\n",
    "    final_cols = [c for c in ['Accuracy (P@10)'] + metrics if c in aggregate.columns]\n",
    "    final_table = aggregate[final_cols] * 100\n",
    "    \n",
    "    print(\"=== Final Model Performance Comparison (All Profiles) ===\")\n",
    "    display(final_table.round(2).astype(str) + '%')\n",
    "\n",
    "    # 4. PLOTTING THE BARCHART\n",
    "    plt.figure(figsize=(14, 8), facecolor='#FAFAF8')\n",
    "    ax = plt.gca()\n",
    "    ax.set_facecolor('#FAFAF8')\n",
    "    \n",
    "    # Transpose for plotting: rows = metrics, columns = models\n",
    "    plot_data = final_table.T\n",
    "    \n",
    "    x = np.arange(len(plot_data.index))\n",
    "    width = 0.25\n",
    "    \n",
    "    # Colors requested: Red, Blue, Green\n",
    "    colors = {'BOW': '#D85A30', 'TFIDF': '#185FA5', 'SBERT': '#1D9E75'}\n",
    "    # Mapping labels to colors for consistency if models exist\n",
    "    m_list = list(plot_data.columns)\n",
    "    \n",
    "    for i, model in enumerate(m_list):\n",
    "        pos = x + (i - len(m_list)/2 + 0.5) * width\n",
    "        vals = plot_data[model].values\n",
    "        bars = ax.bar(pos, vals, width, label=model, color=colors.get(model, '#999'), zorder=3)\n",
    "        \n",
    "        # Add values above bins\n",
    "        for bar in bars:\n",
    "            height = bar.get_height()\n",
    "            ax.text(bar.get_x() + bar.get_width()/2., height + 1,\n",
    "                    f'{height:.1f}%', ha='center', va='bottom', \n",
    "                    fontweight='bold', fontsize=10, color=bar.get_facecolor())\n",
    "\n",
    "    ax.set_xticks(x)\n",
    "    ax.set_xticklabels(plot_data.index, fontsize=11, fontweight='bold')\n",
    "    ax.set_ylabel('Score (%)', fontsize=12, fontweight='bold')\n",
    "    ax.set_title('Global Performance Comparison: BOW vs TF-IDF vs SBERT', fontsize=14, pad=20, fontweight='bold')\n",
    "    ax.set_ylim(0, 110)\n",
    "    ax.legend(frameon=False, loc='upper left', fontsize=11)\n",
    "    ax.yaxis.grid(True, linestyle='--', alpha=0.6, zorder=0)\n",
    "    for sp in ax.spines.values(): sp.set_visible(False)\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "    \n",
    "    best_model = aggregate['NDCG @10'].idxmax() if 'NDCG @10' in aggregate.columns else \"Unknown\"\n",
    "    print(f\"🏆 Best Model (by Ranking Quality): {best_model}\")\n",
    "\n",
    "except Exception as e:\n",
    "    print(f\"❌ An unexpected error occurred: {e}\")\n"
]

nb['cells'][-1]['source'] = new_source

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print("Final cell updated with professional Bar Chart visualization.")
